
name: Health Check

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
      - name: Check Pokedex health at Heroku
        uses: jtalk/url-health-check-action@9f9a163f533fcbf8b3d9fe1bf5458e8c23502698
        with:
          url: https://pokedex-al.herokuapp.com/health/
          follow-redirect: 'no'
          max-attempts: 3
          retry-delay: 5s
          retry-all: 'no'

      - name: Notify in Slack about a failure
        uses: 8398a7/action-slack@047b09b154480ed39076984b64f324fff010d703
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          text: A scheduled Pokedex health check for Heroku deployment failed!
          fields: workflow,job
        if: failure()
