
name: Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the sources
        uses: actions/checkout@v2

      - name: fail
        run: asdfghjk
      # - name: Install Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: '12.x'

      # - name: Install dependencies
      #   run: npm install

      # - name: Lint the code
      #   run: npm run eslint

      # - name: Create deliverables for production
      #   run: npm run build

      # - name: Run unit tests
      #   run: npm test

      # - name: Run end-to-end tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     start: npm run start-prod
      #     wait-on: "http://localhost:5000"
      #     command: npm run test:e2e
      #     spec: cypress/integration/*.js

      # - name: Increase the version and create a tag
      #   if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
      #   uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     DEFAULT_BUMP: patch

      # - name: Deploy to Heroku
      #   if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
      #   uses: akhileshns/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
      #   with:
      #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      #     heroku_app_name: "pokedex-al"
      #     heroku_email: "aleksi.lukkarinen@gmail.com"
      #     healthcheck: "https://pokedex-al.herokuapp.com/health"
      #     checkstring: "ok"
      #     rollbackonhealthcheckfailed: true

      # - name: Notify in Slack about a success
      #   uses: 8398a7/action-slack@047b09b154480ed39076984b64f324fff010d703
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   with:
      #     status: custom
      #     fields: repo,commit,ref,workflow,message,author,job,took
      #     custom_payload: |
      #       {
      #         text: `A new Pokedex version (${ process.env.AS_COMMIT }) has been deployed to https://pokedex-al.herokuapp.com/`,
      #         attachments: [{
      #           color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
      #           text: `From: ${ process.env.AS_REPO }@${ process.env.AS_REF }\nBy: ${ process.env.AS_WORKFLOW }/${ process.env.AS_JOB }\nBuild took ${ process.env.AS_TOOK }.\n\nCommit author: ${ process.env.AS_AUTHOR }\nCommit message: ${ process.env.AS_MESSAGE }`,
      #         }]
      #       }
      #   if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') && job.status == 'success' }}

      - name: Notify in Slack about a failure
        uses: 8398a7/action-slack@047b09b154480ed39076984b64f324fff010d703
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          text: Pokedex build of version (${{ env.AS_COMMIT }}) failed!
          fields: repo,commit,ref,workflow,message,author,job,took
        if: failure()
